#!/usr/bin/env bash
# Install Nginx on Web-Sever-01

# Update Packages before Installations
sudo apt-get update
sudo apt-get -y install nginx

# Configur the Uncomplicated Firewall (UFW) to allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Test Nginx configurations to catch Syntax errors
sudo nginx -t

# Restart Nginx
sudo service nginx restart

# Wait for Nginx to start
sleep 5

# Check the content of the index.html file
content=$(curl -s http://localhost)

# Compare the content with the expected string
if [[ "$content" == *"Hello World!"* ]]; then
    echo "Nginx installation and configuration completed successfully."
else
    echo "Error: Nginx configuration or content check failed."
fi