#!/usr/bin/env bash
#  A Script that configures a new Ubuntu machine to Perform  301-redirection

# Upadate Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Create an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performe a 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/ToqaZidan permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart